const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const CREATE_STREAM = 'CREATE_STREAM';
const DELETE_STREAM_BY_ID = 'DELETE_STREAM_BY_ID';
const FETCH_STREAM = 'FETCH_STREAM';
const EDIT_STREAM = 'EDIT_STREAM';
const FETCH_STREAMS = 'FETCH_STREAMS';
const OPEN_POPUP = 'OPEN_POPUP';
const CLOSE_POPUP = 'CLOSE_POPUP';



export {SIGN_IN, SIGN_OUT, CREATE_STREAM, DELETE_STREAM_BY_ID, EDIT_STREAM, FETCH_STREAM, FETCH_STREAMS, OPEN_POPUP, CLOSE_POPUP}